sudo: false
addons:
  apt_packages:
    - libxcursor-dev
    - libx11-dev
language: go
go:
  - 1.9
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get -d -t ./...
script:
  - # go get -t -v ./...
  - # diff -u <(echo -n) <(gofmt -d -s .)
  - # go tool vet .
  - go build -o Build/Build.exe Source/main.go