sudo: false
addons:
  apt_packages:
    - xorg-dev
language: go
go:
  - 1.9
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get -d -t ./...
script:
  - go build -o Build/Build.exe Source/main.go